export const FETCH_WEATHER_INITIAL_REQUESTED = 'FETCH_WEATHER_INITIAL_REQUESTED';
export const FETCH_WEATHER_INITIAL_SUCCEEDED = 'FETCH_WEATHER_INITIAL_SUCCEEDED';
export const FETCH_WEATHER_INITIAL_FAILED = 'FETCH_WEATHER_INITIAL_FAILED';

<<<<<<< HEAD
=======
export const FETCH_FORECAST_REQUESTED = 'FETCH_FORECAST_REQUESTED';
export const FETCH_FORECAST_SUCCEEDED = 'FETCH_FORECAST_SUCCEEDED';
export const FETCH_FORECAST_FAILED = 'FETCH_FORECAST_FAILED';

>>>>>>> 79613553a1550b1e794e80b40226dda1ccdc7dce
export const FETCH_WEATHER_REQUESTED = 'FETCH_WEATHER_REQUESTED';
export const FETCH_WEATHER_SUCCEEDED = 'FETCH_WEATHER_SUCCEEDED';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';
