export const FETCH_WEATHER_INITIAL_REQUESTED = 'FETCH_WEATHER_INITIAL_REQUESTED';
export const FETCH_WEATHER_INITIAL_SUCCEEDED = 'FETCH_WEATHER_INITIAL_SUCCEEDED';
export const FETCH_WEATHER_INITIAL_FAILED = 'FETCH_WEATHER_INITIAL_FAILED';

export const FETCH_WEATHER_REQUESTED = 'FETCH_WEATHER_REQUESTED';
export const FETCH_WEATHER_SUCCEEDED = 'FETCH_WEATHER_SUCCEEDED';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';
